# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogonForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logon(object):
    def setupUi(self, Logon):
        Logon.setObjectName("Logon")
        Logon.resize(563, 403)
        self.centralwidget = QtWidgets.QWidget(Logon)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hint = QtWidgets.QLabel(self.frame)
        self.hint.setAlignment(QtCore.Qt.AlignCenter)
        self.hint.setObjectName("hint")
        self.verticalLayout_4.addWidget(self.hint)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip.sizePolicy().hasHeightForWidth())
        self.ip.setSizePolicy(sizePolicy)
        self.ip.setObjectName("ip")
        self.horizontalLayout.addWidget(self.ip)
        self.port = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setObjectName("port")
        self.horizontalLayout.addWidget(self.port)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.nextb = QtWidgets.QPushButton(self.frame)
        self.nextb.setObjectName("nextb")
        self.verticalLayout_4.addWidget(self.nextb)
        self.autologin = QtWidgets.QCheckBox(self.frame)
        self.autologin.setObjectName("autologin")
        self.verticalLayout_4.addWidget(self.autologin)
        self.status = QtWidgets.QLabel(self.frame)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.verticalLayout_4.addWidget(self.status)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(4, 5)
        self.gridLayout_2.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hint1 = QtWidgets.QLabel(self.centralwidget)
        self.hint1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.hint1.setObjectName("hint1")
        self.verticalLayout_5.addWidget(self.hint1)
        self.saves = QtWidgets.QComboBox(self.centralwidget)
        self.saves.setEnabled(False)
        self.saves.setAutoFillBackground(False)
        self.saves.setObjectName("saves")
        self.verticalLayout_5.addWidget(self.saves)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 4, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setObjectName("settings")
        self.gridLayout_3.addWidget(self.settings, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 2)
        Logon.setCentralWidget(self.centralwidget)

        self.retranslateUi(Logon)
        QtCore.QMetaObject.connectSlotsByName(Logon)

    def retranslateUi(self, Logon):
        _translate = QtCore.QCoreApplication.translate
        Logon.setWindowTitle(_translate("Logon", "MainWindow"))
        self.hint.setText(_translate("Logon", "Enter ip/domen"))
        self.ip.setPlaceholderText(_translate("Logon", "ex.127.0.0.1"))
        self.port.setText(_translate("Logon", "19130"))
        self.nextb.setText(_translate("Logon", "Connect"))
        self.autologin.setText(_translate("Logon", "Remember me"))
        self.status.setText(_translate("Logon", "EMPTY"))
        self.hint1.setText(_translate("Logon", "Saved ips"))
        self.settings.setText(_translate("Logon", "Settings"))
