# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerPanel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.console = QtWidgets.QListWidget(self.centralwidget)
        self.console.setObjectName("console")
        self.gridLayout.addWidget(self.console, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkupdates = QtWidgets.QPushButton(self.centralwidget)
        self.checkupdates.setObjectName("checkupdates")
        self.horizontalLayout.addWidget(self.checkupdates)
        self.console_input = QtWidgets.QLineEdit(self.centralwidget)
        self.console_input.setObjectName("console_input")
        self.horizontalLayout.addWidget(self.console_input)
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setObjectName("restart")
        self.horizontalLayout.addWidget(self.restart)
        self.start_stop = QtWidgets.QPushButton(self.centralwidget)
        self.start_stop.setObjectName("start_stop")
        self.horizontalLayout.addWidget(self.start_stop)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.set_startup = QtWidgets.QPushButton(self.centralwidget)
        self.set_startup.setObjectName("set_startup")
        self.horizontalLayout_2.addWidget(self.set_startup)
        self.set_backup = QtWidgets.QPushButton(self.centralwidget)
        self.set_backup.setObjectName("set_backup")
        self.horizontalLayout_2.addWidget(self.set_backup)
        self.set_checkupdate = QtWidgets.QPushButton(self.centralwidget)
        self.set_checkupdate.setObjectName("set_checkupdate")
        self.horizontalLayout_2.addWidget(self.set_checkupdate)
        self.set_reboot = QtWidgets.QPushButton(self.centralwidget)
        self.set_reboot.setObjectName("set_reboot")
        self.horizontalLayout_2.addWidget(self.set_reboot)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.levelname = QtWidgets.QLabel(self.frame)
        self.levelname.setAlignment(QtCore.Qt.AlignCenter)
        self.levelname.setObjectName("levelname")
        self.verticalLayout.addWidget(self.levelname)
        self.open_gamerules = QtWidgets.QPushButton(self.frame)
        self.open_gamerules.setObjectName("open_gamerules")
        self.verticalLayout.addWidget(self.open_gamerules)
        self.open_packs = QtWidgets.QPushButton(self.frame)
        self.open_packs.setObjectName("open_packs")
        self.verticalLayout.addWidget(self.open_packs)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.players_label = QtWidgets.QLabel(self.frame)
        self.players_label.setObjectName("players_label")
        self.verticalLayout.addWidget(self.players_label)
        self.players = QtWidgets.QListWidget(self.frame)
        self.players.setObjectName("players")
        self.verticalLayout.addWidget(self.players)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.kick = QtWidgets.QPushButton(self.frame)
        self.kick.setObjectName("kick")
        self.horizontalLayout_4.addWidget(self.kick)
        self.ban = QtWidgets.QPushButton(self.frame)
        self.ban.setObjectName("ban")
        self.horizontalLayout_4.addWidget(self.ban)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.worlds_label = QtWidgets.QLabel(self.frame)
        self.worlds_label.setObjectName("worlds_label")
        self.verticalLayout.addWidget(self.worlds_label)
        self.worlds = QtWidgets.QListWidget(self.frame)
        self.worlds.setObjectName("worlds")
        self.verticalLayout.addWidget(self.worlds)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.select = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select.sizePolicy().hasHeightForWidth())
        self.select.setSizePolicy(sizePolicy)
        self.select.setMinimumSize(QtCore.QSize(61, 0))
        self.select.setObjectName("select")
        self.horizontalLayout_5.addWidget(self.select)
        self.new = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new.sizePolicy().hasHeightForWidth())
        self.new.setSizePolicy(sizePolicy)
        self.new.setMinimumSize(QtCore.QSize(61, 0))
        self.new.setObjectName("new")
        self.horizontalLayout_5.addWidget(self.new)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.delete = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete.sizePolicy().hasHeightForWidth())
        self.delete.setSizePolicy(sizePolicy)
        self.delete.setMinimumSize(QtCore.QSize(61, 0))
        self.delete.setObjectName("delete")
        self.horizontalLayout_5.addWidget(self.delete)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 6)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(6, 2)
        self.verticalLayout.setStretch(7, 2)
        self.verticalLayout.setStretch(9, 2)
        self.verticalLayout.setStretch(10, 2)
        self.gridLayout.addWidget(self.frame, 1, 1, 2, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        self.exit.setMinimumSize(QtCore.QSize(52, 0))
        self.exit.setObjectName("exit")
        self.horizontalLayout_3.addWidget(self.exit)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 11)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkupdates.setText(_translate("MainWindow", "Check updates"))
        self.console_input.setPlaceholderText(_translate("MainWindow", "Enter console command..."))
        self.restart.setText(_translate("MainWindow", "Restart"))
        self.start_stop.setText(_translate("MainWindow", "Start"))
        self.set_startup.setText(_translate("MainWindow", "Startup action"))
        self.set_backup.setText(_translate("MainWindow", "Backup interval"))
        self.set_checkupdate.setText(_translate("MainWindow", "Checkupate interval"))
        self.set_reboot.setText(_translate("MainWindow", "Reboot interval"))
        self.levelname.setText(_translate("MainWindow", "LEVELNAME"))
        self.open_gamerules.setText(_translate("MainWindow", "Gamerules"))
        self.open_packs.setText(_translate("MainWindow", "Packs"))
        self.players_label.setText(_translate("MainWindow", "Players"))
        self.kick.setText(_translate("MainWindow", "Kick"))
        self.ban.setText(_translate("MainWindow", "Ban"))
        self.worlds_label.setText(_translate("MainWindow", "Worlds"))
        self.select.setText(_translate("MainWindow", "Select"))
        self.new.setText(_translate("MainWindow", "New"))
        self.delete.setText(_translate("MainWindow", "Delete"))
        self.exit.setText(_translate("MainWindow", "EXIT"))